-- FastReadingREST -- PostgreSQL schema
--
-- The application runs with `spring.jpa.hibernate.ddl-auto=validate`, so it
-- will NOT create these tables for you: the schema must exist before first
-- boot or startup fails with a SchemaManagementException.
--
-- Apply with:  psql "$DB_URL" -f db/schema.sql

CREATE TABLE IF NOT EXISTS users (
    id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS documents (
    id                   INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Owner of a PRIVATE document. NULL for PUBLIC samples.
    user_id              INTEGER,
    -- Admin who uploaded a PUBLIC sample. NULL for PRIVATE documents.
    uploaded_by_admin_id INTEGER,
    title                VARCHAR(255) NOT NULL,
    word_count           INTEGER      NOT NULL DEFAULT 0,
    -- PROCESSING | READY | FAILED
    status               VARCHAR(20)  NOT NULL DEFAULT 'PROCESSING',
    -- PRIVATE | PUBLIC
    visibility           VARCHAR(10)  NOT NULL DEFAULT 'PRIVATE',
    is_sample            BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_documents_users
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_documents_uploaded_by_admin
        FOREIGN KEY (uploaded_by_admin_id) REFERENCES users (id)
);

-- One row per ~1200-word slice of a document (see PdfChunkingService).
CREATE TABLE IF NOT EXISTS document_chunks (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id      INTEGER NOT NULL,
    -- 0-based position of this chunk within the document.
    chunk_index      INTEGER NOT NULL,
    -- Absolute word offset of this chunk's first word within the document.
    start_word_index INTEGER NOT NULL,
    word_count       INTEGER NOT NULL,
    chunk_text       TEXT    NOT NULL,
    CONSTRAINT fk_document_chunks_documents
        FOREIGN KEY (document_id) REFERENCES documents (id),
    CONSTRAINT uq_document_chunks_doc_chunk UNIQUE (document_id, chunk_index)
);

-- Supports ChunkReadService's "chunk at or before this word index" lookup.
CREATE INDEX IF NOT EXISTS ix_document_chunks_doc_start
    ON document_chunks (document_id, start_word_index DESC);

CREATE TABLE IF NOT EXISTS reading_sessions (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER     NOT NULL,
    document_id INTEGER     NOT NULL,
    started_at  TIMESTAMP   NOT NULL DEFAULT NOW(),
    ended_at    TIMESTAMP,
    avg_wpm     INTEGER,
    words_read  INTEGER     NOT NULL DEFAULT 0,
    -- SPEED | NORMAL
    mode        VARCHAR(10) NOT NULL,
    CONSTRAINT fk_reading_sessions_users
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reading_sessions_documents
        FOREIGN KEY (document_id) REFERENCES documents (id)
);

-- Drives the admin daily-words report, which filters on ended_at.
CREATE INDEX IF NOT EXISTS ix_reading_sessions_ended_at
    ON reading_sessions (ended_at);

-- Resume point: one row per (user, document).
-- The composite primary key is required -- ReadingProgressRepository.upsert
-- relies on `ON CONFLICT (user_id, document_id)`.
CREATE TABLE IF NOT EXISTS reading_progress (
    user_id            INTEGER   NOT NULL,
    document_id        INTEGER   NOT NULL,
    current_word_index INTEGER   NOT NULL DEFAULT 0,
    last_wpm           INTEGER,
    updated_at         TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, document_id),
    CONSTRAINT fk_reading_progress_users
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reading_progress_documents
        FOREIGN KEY (document_id) REFERENCES documents (id)
);
